import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Zlatna Luka Yachts",
  description: "Generated by Code-Trends",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
